export const API = {
  auth: {
    login: "/auth/login",
  },
  users: {
    registerInit: "/users/register/init",
    registerVerify: "/users/register/verify",
    registerComplete: "/users/register/complete",
    passwordResetRequest: "/users/password-reset/request",
    passwordResetConfirm: "/users/password-reset/confirm",
  },
  gardenProjects: {
    list: "/garden-projects",
    detail: (id: string) => `/garden-projects/${id}`,
    construction: (id: string) => `/garden-projects/${id}/construction`,
    calculate: (id: string) => `/garden-projects/${id}/calculate`,
  },
  tilePlans: {
    list: "/tile-plans",
    detail: (id: string) => `/tile-plans/${id}`,
  },
  quoteRequests: {
    create: "/quote-requests",
    mine: "/quote-requests/mine",
    detail: (id: string) => `/quote-requests/mine/${id}`,
    acceptProposal: (jobId: string, proposalId: string) =>
      `/quote-requests/mine/${jobId}/proposals/${proposalId}/accept`,
    startWork: (id: string) => `/quote-requests/mine/${id}/start`,
    completeWork: (id: string) => `/quote-requests/mine/${id}/complete`,
    closeJob: (id: string) => `/quote-requests/mine/${id}/close`,
    review: (id: string) => `/quote-requests/mine/${id}/review`,
    addPhoto: (id: string) => `/quote-requests/mine/${id}/photos`,
    removePhoto: (id: string) => `/quote-requests/mine/${id}/photos`,
    nearby: "/quote-requests/nearby",
    nearbyDetail: (id: string) => `/quote-requests/nearby/${id}`,
    contractorStartWork: (id: string) => `/quote-requests/nearby/${id}/start`,
    propose: (id: string) => `/quote-requests/nearby/${id}/propose`,
    updateProposal: (id: string) => `/quote-requests/nearby/${id}/proposal`,
    withdrawProposal: (id: string) => `/quote-requests/nearby/${id}/proposal`,
    myProposals: "/quote-requests/my-proposals",
    myReviews: "/quote-requests/my-reviews",
    replyToReview: (id: string) => `/quote-requests/reviews/${id}/reply`,
    directToMe: "/quote-requests/direct-to-me",
    createDirect: "/quote-requests/direct",
    acceptDirect: (id: string) => `/quote-requests/direct/${id}/accept`,
  },
  chat: {
    rooms: "/chat/rooms",
    roomMessages: (id: string) => `/chat/rooms/${id}/messages`,
  },
  notifications: {
    list: "/notifications",
    unreadCount: "/notifications/unread-count",
    markRead: (id: string) => `/notifications/${id}/read`,
    markAllRead: "/notifications/read-all",
  },
  pricing: {
    materials: "/pricing/materials",
    tools: "/pricing/tools",
    labour: "/pricing/labour",
    lastUpdate: "/pricing/last-update",
    updateMaterial: (id: string) => `/pricing/materials/${id}`,
    updateTool: (id: string) => `/pricing/tools/${id}`,
    updateLabour: (id: string) => `/pricing/labour/${id}`,
  },
  contractors: {
    me: "/contractor-profiles/me",
    near: "/contractor-profiles/near",
    public: (id: string) => `/contractor-profiles/public/${id}`,
    savedList: "/contractor-profiles/saved/list",
    savedIds: "/contractor-profiles/saved/ids",
    save: (id: string) => `/contractor-profiles/saved/${id}`,
    unsave: (id: string) => `/contractor-profiles/saved/${id}`,
  },
} as const;
